/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufmt.ic.alg3.videoJogos.view.cadastro;

/**
 *
 * @author Moacyr
 */
public class FormaDePagamentoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BoletoBancarioJPanel
     */
    public FormaDePagamentoJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        formaDePagamentojLabel = new javax.swing.JLabel();
        cartaoDeCreditojButton = new javax.swing.JButton();
        boletoBancariojButton = new javax.swing.JButton();
        depositoEmContajButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        formaDePagamentojLabel.setText("Forma de Pagamento");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 119;
        gridBagConstraints.ipady = 34;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 21, 0, 0);
        add(formaDePagamentojLabel, gridBagConstraints);

        cartaoDeCreditojButton.setText("Cartão de Crédito");
        cartaoDeCreditojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartaoDeCreditojButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 104, 0, 0);
        add(cartaoDeCreditojButton, gridBagConstraints);

        boletoBancariojButton.setText("Boleto Bancário");
        boletoBancariojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boletoBancariojButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 31;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 104, 0, 0);
        add(boletoBancariojButton, gridBagConstraints);

        depositoEmContajButton.setText("Depósito em Conta");
        depositoEmContajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositoEmContajButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 104, 64, 0);
        add(depositoEmContajButton, gridBagConstraints);

        jLabel1.setText("Selecione uma forma de pagamento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 80, 0, 96);
        add(jLabel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void depositoEmContajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositoEmContajButtonActionPerformed
        this.removeAll();
        this.add(new DepositoEmContaJPanel());
        this.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_depositoEmContajButtonActionPerformed

    private void cartaoDeCreditojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartaoDeCreditojButtonActionPerformed
        this.removeAll();
        this.add(new CartaoDeCreditoJPanel());
        this.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_cartaoDeCreditojButtonActionPerformed

    private void boletoBancariojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boletoBancariojButtonActionPerformed
this.removeAll();
        this.add(new BoletoBancarioJPanel());
        this.setVisible(false);
        this.setVisible(true);    }//GEN-LAST:event_boletoBancariojButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boletoBancariojButton;
    private javax.swing.JButton cartaoDeCreditojButton;
    private javax.swing.JButton depositoEmContajButton;
    private javax.swing.JLabel formaDePagamentojLabel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
