/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufmt.alg3.videoJogos.view;

/**
 *
 * @author Moacyr
 */
public class PrincipalJFrame extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalJFrame
     */
    public PrincipalJFrame() {
        initComponents();
        conteudojPanel.removeAll();
        conteudojPanel.add(new inicioJPanel());
        conteudojPanel.setVisible(false);
        conteudojPanel.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conteudojPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        cadastrarjMenu = new javax.swing.JMenu();
        usuariojMenuItem = new javax.swing.JMenuItem();
        jogojMenuItem = new javax.swing.JMenuItem();
        entrarjMenu = new javax.swing.JMenu();
        EntrarjMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 450));
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        conteudojPanel.setLayout(new javax.swing.BoxLayout(conteudojPanel, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(conteudojPanel);

        jMenuBar1.setForeground(new java.awt.Color(0, 0, 100));

        cadastrarjMenu.setText("Cadastrar");

        usuariojMenuItem.setText("Usuario");
        usuariojMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariojMenuItemActionPerformed(evt);
            }
        });
        cadastrarjMenu.add(usuariojMenuItem);

        jogojMenuItem.setText("Jogo");
        jogojMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogojMenuItemActionPerformed(evt);
            }
        });
        cadastrarjMenu.add(jogojMenuItem);

        jMenuBar1.add(cadastrarjMenu);

        entrarjMenu.setText("Entrar");
        entrarjMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarjMenuActionPerformed(evt);
            }
        });

        EntrarjMenuItem.setText("Entrar");
        EntrarjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarjMenuItemActionPerformed(evt);
            }
        });
        entrarjMenu.add(EntrarjMenuItem);

        jMenuBar1.add(entrarjMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*
    
    private void responsaveljMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO add your handling code here:
        conteudojPanel.removeAll();
        conteudojPanel.add(new ResponsavelJPanel());
        conteudojPanel.setVisible(false);
        conteudojPanel.setVisible(true);
    }
    */
    private void usuariojMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariojMenuItemActionPerformed
        conteudojPanel.removeAll();
        conteudojPanel.add(new UsuarioJPanel());
        conteudojPanel.setVisible(false);
        conteudojPanel.setVisible(true);

    }//GEN-LAST:event_usuariojMenuItemActionPerformed

    private void jogojMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jogojMenuItemActionPerformed
        conteudojPanel.removeAll();
        conteudojPanel.add(new JogoJPanel());
        conteudojPanel.setVisible(false);
        conteudojPanel.setVisible(true);
    }//GEN-LAST:event_jogojMenuItemActionPerformed

    private void entrarjMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarjMenuActionPerformed
        conteudojPanel.removeAll();
        conteudojPanel.add(new EntrarJPanel());
        conteudojPanel.setVisible(false);
        conteudojPanel.setVisible(true);
    }//GEN-LAST:event_entrarjMenuActionPerformed

    private void EntrarjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarjMenuItemActionPerformed
        conteudojPanel.removeAll();
        conteudojPanel.add(new EntrarJPanel());
        conteudojPanel.setVisible(false);
        conteudojPanel.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_EntrarjMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem EntrarjMenuItem;
    private javax.swing.JMenu cadastrarjMenu;
    private javax.swing.JPanel conteudojPanel;
    private javax.swing.JMenu entrarjMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jogojMenuItem;
    private javax.swing.JMenuItem usuariojMenuItem;
    // End of variables declaration//GEN-END:variables
}
