/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufmt.ic.alg3.videoJogos.view;

import br.ufmt.ic.alg3.videoJogos.model.entidades.CartaoDeCredito;
import br.ufmt.ic.alg3.videoJogos.persistencia.CartaoDeCreditoPersistencia;
import br.ufmt.ic.alg3.videoJogos.persistencia.arquivo.CartaoDeCreditoPersistenciaArquivo;
import javax.swing.JOptionPane;

/**
 *
 * @author Moacyr
 */
public class inicioJPanel extends javax.swing.JPanel {

    private static CartaoDeCreditoPersistencia banco = new CartaoDeCreditoPersistenciaArquivo();

    /**
     * Creates new form inicioJPanel
     */
    public inicioJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jComboBox1 = new javax.swing.JComboBox<>();
        expiryDatejTextField = new javax.swing.JTextField();
        securityCodejPasswordField = new javax.swing.JPasswordField();
        thThanksjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        conteudoPrincipaljLabel = new javax.swing.JLabel();
        cardtNumberjTextField = new javax.swing.JTextField();
        textoKizunaKawaiijLabel = new javax.swing.JLabel();
        textoKizunaKawaii2jLabel = new javax.swing.JLabel();
        textoKizunaKawaii3jLabel = new javax.swing.JLabel();
        cardNumberjLabel = new javax.swing.JLabel();
        expiryDatejLabel = new javax.swing.JLabel();
        securiryCodejLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.GridBagLayout());

        expiryDatejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expiryDatejTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 132;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 6, 0, 0);
        add(expiryDatejTextField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 132;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 6, 0, 0);
        add(securityCodejPasswordField, gridBagConstraints);

        thThanksjButton.setText("Th-thanks");
        thThanksjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thThanksjButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 56, 0, 0);
        add(thThanksjButton, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(50, 0, 200));
        jLabel1.setText("NosTeam");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 60, 0, 0);
        add(jLabel1, gridBagConstraints);

        conteudoPrincipaljLabel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        conteudoPrincipaljLabel.setForeground(new java.awt.Color(200, 0, 0));
        conteudoPrincipaljLabel.setText("Vídeo Jogos muito divertidos!");
        conteudoPrincipaljLabel.setAlignmentX(0.5F);
        conteudoPrincipaljLabel.setBorder(new javax.swing.border.MatteBorder(null));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 120, 0, 0);
        add(conteudoPrincipaljLabel, gridBagConstraints);

        cardtNumberjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardtNumberjTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 132;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 0);
        add(cardtNumberjTextField, gridBagConstraints);

        textoKizunaKawaiijLabel.setText("H-hi there...");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 32;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(134, 6, 0, 0);
        add(textoKizunaKawaiijLabel, gridBagConstraints);

        textoKizunaKawaii2jLabel.setText("Do you th-think i could have your");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = 21;
        gridBagConstraints.ipady = -2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        add(textoKizunaKawaii2jLabel, gridBagConstraints);

        textoKizunaKawaii3jLabel.setText("credit card information, p-please?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.ipadx = 39;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        add(textoKizunaKawaii3jLabel, gridBagConstraints);

        cardNumberjLabel.setText("Card number:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 58, 0, 0);
        add(cardNumberjLabel, gridBagConstraints);

        expiryDatejLabel.setText("Expiry date:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 65, 0, 0);
        add(expiryDatejLabel, gridBagConstraints);

        securiryCodejLabel.setText("Security code:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 55, 0, 0);
        add(securiryCodejLabel, gridBagConstraints);

        jButton1.setText("Loja");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 115;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 38, 0, 0);
        add(jButton1, gridBagConstraints);

        jButton2.setText("Encontrar Amigos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.ipadx = 22;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 10, 0, 0);
        add(jButton2, gridBagConstraints);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufmt/ic/alg3/videoJogos/view/sunohara mei.resized.png"))); // NOI18N
        jLabel8.setMaximumSize(new java.awt.Dimension(300, 240));
        jLabel8.setMinimumSize(new java.awt.Dimension(300, 240));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 16;
        gridBagConstraints.gridheight = 11;
        gridBagConstraints.ipadx = 47;
        gridBagConstraints.ipady = 280;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 18, 0, 105);
        add(jLabel8, gridBagConstraints);
        jLabel8.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void cardtNumberjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardtNumberjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardtNumberjTextFieldActionPerformed

    private void thThanksjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thThanksjButtonActionPerformed
        // TODO add your handling code here:
        CartaoDeCredito novo = new CartaoDeCredito();

        novo.setCodigoDeSeguranca((new Integer(securityCodejPasswordField.getText())));
        novo.setDataEx((new Integer(expiryDatejTextField.getText())));
        novo.setNumCartao((new Integer(cardtNumberjTextField.getText())));
        //cliente.setIdade(new Integer(txtIdade.getText()).intValue());

        cardtNumberjTextField.setText("");
        expiryDatejTextField.setText("");
        securityCodejPasswordField.setText("");

        banco.inserir(novo);
        JOptionPane.showMessageDialog(thThanksjButton, "Onee-chan! (◕‿◕✿)");
    }//GEN-LAST:event_thThanksjButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        this.removeAll();
        this.add(new LojaJPanel());
        this.setVisible(false);
        this.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.removeAll();
        this.add(new ProcurarAmigosJPanel());
        this.setVisible(false);
        this.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void expiryDatejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expiryDatejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expiryDatejTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cardNumberjLabel;
    private javax.swing.JTextField cardtNumberjTextField;
    private javax.swing.JLabel conteudoPrincipaljLabel;
    private javax.swing.JLabel expiryDatejLabel;
    private javax.swing.JTextField expiryDatejTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel securiryCodejLabel;
    private javax.swing.JPasswordField securityCodejPasswordField;
    private javax.swing.JLabel textoKizunaKawaii2jLabel;
    private javax.swing.JLabel textoKizunaKawaii3jLabel;
    private javax.swing.JLabel textoKizunaKawaiijLabel;
    private javax.swing.JButton thThanksjButton;
    // End of variables declaration//GEN-END:variables
}
