/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufmt.ic.alg3.videoJogos.view;

import br.ufmt.ic.alg3.videoJogos.model.entidades.CartaoDeCredito;
import javax.swing.JOptionPane;


/**
 *
 * @author Moacyr
 */
public class inicioJPanel extends javax.swing.JPanel {

    /**
     * Creates new form inicioJPanel
     */
    public inicioJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        expiryDatejTextField = new javax.swing.JTextField();
        securityCodejPasswordField = new javax.swing.JPasswordField();
        thThanksjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        conteudoPrincipaljLabel = new javax.swing.JLabel();
        cardtNumberjTextField = new javax.swing.JTextField();
        textoKizunaKawaiijLabel = new javax.swing.JLabel();
        textoKizunaKawaii2jLabel = new javax.swing.JLabel();
        textoKizunaKawaii3jLabel = new javax.swing.JLabel();
        cardNumberjLabel = new javax.swing.JLabel();
        expiryDatejLabel = new javax.swing.JLabel();
        securiryCodejLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setMinimumSize(new java.awt.Dimension(600, 450));
        setPreferredSize(new java.awt.Dimension(600, 450));

        thThanksjButton.setText("Th-thanks");
        thThanksjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thThanksjButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(50, 0, 200));
        jLabel1.setText("NosTeam");

        conteudoPrincipaljLabel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        conteudoPrincipaljLabel.setForeground(new java.awt.Color(200, 0, 0));
        conteudoPrincipaljLabel.setText("Vídeo Jogos muito divertidos!");
        conteudoPrincipaljLabel.setAlignmentX(0.5F);
        conteudoPrincipaljLabel.setBorder(new javax.swing.border.MatteBorder(null));

        cardtNumberjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardtNumberjTextFieldActionPerformed(evt);
            }
        });

        textoKizunaKawaiijLabel.setText("H-hi there...");

        textoKizunaKawaii2jLabel.setText("Do you th-think i could have your");

        textoKizunaKawaii3jLabel.setText("credit card information, p-please?");

        cardNumberjLabel.setText("Card number:");

        expiryDatejLabel.setText("Expiry date:");

        securiryCodejLabel.setText("Security code:");

        jButton1.setText("Loja");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Encontrar Amigos");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufmt/ic/alg3/videoJogos/view/imagemTelaPrincipal.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(conteudoPrincipaljLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(thThanksjButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(securiryCodejLabel)
                                .addGap(1, 1, 1)
                                .addComponent(securityCodejPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(textoKizunaKawaiijLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(textoKizunaKawaii2jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(textoKizunaKawaii3jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cardNumberjLabel)
                                .addGap(4, 4, 4)
                                .addComponent(cardtNumberjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(expiryDatejLabel)
                                .addGap(1, 1, 1)
                                .addComponent(expiryDatejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(211, 211, 211))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(134, 134, 134)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(conteudoPrincipaljLabel)
                        .addGap(101, 101, 101)
                        .addComponent(textoKizunaKawaiijLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(textoKizunaKawaii2jLabel)
                        .addGap(6, 6, 6)
                        .addComponent(textoKizunaKawaii3jLabel)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cardNumberjLabel)
                            .addComponent(cardtNumberjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(expiryDatejLabel)
                            .addComponent(expiryDatejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(securiryCodejLabel)
                            .addComponent(securityCodejPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(429, 429, 429)
                .addComponent(thThanksjButton))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cardtNumberjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardtNumberjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardtNumberjTextFieldActionPerformed

    private void thThanksjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thThanksjButtonActionPerformed
        // TODO add your handling code here:
        CartaoDeCredito novo = new CartaoDeCredito();
        
        novo.setCodigoDeSeguranca((new Integer(securityCodejPasswordField.getText())));
        novo.setDataEx((new Integer(expiryDatejTextField.getText())));
        novo.setNumCartao((new Integer(cardtNumberjTextField.getText())));
        //cliente.setIdade(new Integer(txtIdade.getText()).intValue());
        
       cardtNumberjTextField.setText("");
       expiryDatejTextField.setText("");
       securityCodejPasswordField.setText("");
       
       JOptionPane.showMessageDialog(thThanksjButton, "Onee-chan! (◕‿◕✿)");   
    }//GEN-LAST:event_thThanksjButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cardNumberjLabel;
    private javax.swing.JTextField cardtNumberjTextField;
    private javax.swing.JLabel conteudoPrincipaljLabel;
    private javax.swing.JLabel expiryDatejLabel;
    private javax.swing.JTextField expiryDatejTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel securiryCodejLabel;
    private javax.swing.JPasswordField securityCodejPasswordField;
    private javax.swing.JLabel textoKizunaKawaii2jLabel;
    private javax.swing.JLabel textoKizunaKawaii3jLabel;
    private javax.swing.JLabel textoKizunaKawaiijLabel;
    private javax.swing.JButton thThanksjButton;
    // End of variables declaration//GEN-END:variables
}
