/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufmt.ic.alg3.videoJogos.view;

import br.ufmt.ic.alg3.videoJogos.model.entidades.Jogo;
import br.ufmt.ic.alg3.videoJogos.persistencia.JogoPersistencia;
import br.ufmt.ic.alg3.videoJogos.persistencia.lista.JogoPersistenciaLista;
import javax.swing.JOptionPane;

/**
 *
 * @author Moacyr
 */
public class JogoJPanel extends javax.swing.JPanel {

    private static JogoPersistencia
            banco = new JogoPersistenciaLista();
    
    /**
     * Creates new form JogoJPanel
     */
    public JogoJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idjLabel = new javax.swing.JLabel();
        nomejLabel = new javax.swing.JLabel();
        idjTextField = new javax.swing.JTextField();
        precojLabel = new javax.swing.JLabel();
        classIndcjLabel = new javax.swing.JLabel();
        tipojLabel = new javax.swing.JLabel();
        nomejTextField = new javax.swing.JTextField();
        precojTextField = new javax.swing.JTextField();
        classIndcjTextField = new javax.swing.JTextField();
        tipojTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        salvarjButton = new javax.swing.JButton();
        cancelarjButton = new javax.swing.JButton();
        desenvolvedornomejLabel = new javax.swing.JLabel();
        desenvolvedorjTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaJogosCadastrojTable = new javax.swing.JTable();
        removerjButton = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(600, 450));
        setPreferredSize(new java.awt.Dimension(600, 450));

        idjLabel.setText("ID:");

        nomejLabel.setText("Nome:");

        idjTextField.setEditable(false);
        idjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idjTextFieldActionPerformed(evt);
            }
        });

        precojLabel.setText("Preço:");

        classIndcjLabel.setText("Classificação Indicativa:");

        tipojLabel.setText("Tipo/Marcadores:");

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 200));
        jLabel1.setText("Cadastrar Vídeo Jogo");

        salvarjButton.setText("Salvar");
        salvarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarjButtonActionPerformed(evt);
            }
        });

        cancelarjButton.setText("Cancelar");
        cancelarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarjButtonActionPerformed(evt);
            }
        });

        desenvolvedornomejLabel.setText("Desenvolvedor:");

        desenvolvedorjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desenvolvedorjTextFieldActionPerformed(evt);
            }
        });

        tabelaJogosCadastrojTable.setModel(new JogoTableModel(banco.getAll()));
        jScrollPane1.setViewportView(tabelaJogosCadastrojTable);

        removerjButton.setText("Remover");
        removerjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(precojLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nomejLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(precojTextField)
                                    .addComponent(nomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tipojLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(salvarjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)
                                        .addComponent(cancelarjButton))
                                    .addComponent(tipojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(desenvolvedornomejLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(desenvolvedorjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idjLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(idjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(classIndcjLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(classIndcjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addContainerGap(341, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(removerjButton)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(25, 25, 25)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idjLabel)
                    .addComponent(idjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomejLabel)
                    .addComponent(nomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precojLabel)
                    .addComponent(precojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(desenvolvedorjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desenvolvedornomejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classIndcjLabel)
                    .addComponent(classIndcjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipojLabel)
                    .addComponent(tipojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salvarjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(removerjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void idjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idjTextFieldActionPerformed

    private void salvarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarjButtonActionPerformed
        // Salvar o jogo aqui
        Jogo novo = new Jogo();
        novo.setNome(nomejTextField.getText());
        novo.setPreco(precojTextField.getText()); //Arrumar essa parte aqui que não ta convertendo
        novo.setTipo(tipojTextField.getText());
        novo.setClassificacaoIndicativa(classIndcjTextField.getText());
        novo.setDesenvolvedor(desenvolvedorjTextField.getText());
         //AQUI VAI FICAR A PARTE DE PERSISTIR NO BANCO DE DADOS
        
      //  banco.remover(novo);
        banco.inserir(novo);
      
        JOptionPane.showMessageDialog( salvarjButton, "Casdastrado com Sucesso!");
        cancelarjButtonActionPerformed(null);
        
        JogoTableModel modelo = 
                (JogoTableModel) tabelaJogosCadastrojTable.getModel();
        
        modelo.fireTableRowsInserted(0, 1);
        
    }//GEN-LAST:event_salvarjButtonActionPerformed

    private void desenvolvedorjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desenvolvedorjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desenvolvedorjTextFieldActionPerformed

    private void cancelarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarjButtonActionPerformed
        
        nomejTextField.setText("");
        precojTextField.setText("");
        classIndcjTextField.setText("");
        tipojTextField.setText("");
        idjTextField.setText("");
        desenvolvedorjTextField.setText("");

        
    }//GEN-LAST:event_cancelarjButtonActionPerformed

    private void removerjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerjButtonActionPerformed
        
    // TODO add your handling code here:
            int[] linhas = tabelaJogosCadastrojTable.getSelectedRows();
        
//        int decremento = 0;
//        for(int i = 0; i < linhas.length;i++){
//            Responsavel removido = banco
//                    .getAll().get(linhas[i]-decremento);
        for(int i = linhas.length - 1; i >= 0;i--){
            Jogo removido = banco
                    .getAll().get(linhas[i]);
            banco.remover(removido);
//            decremento++;
            
            JogoTableModel modelo = 
                (JogoTableModel) tabelaJogosCadastrojTable.getModel();
        
            modelo.fireTableRowsDeleted(0, 1);
        }
    }//GEN-LAST:event_removerjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarjButton;
    private javax.swing.JLabel classIndcjLabel;
    private javax.swing.JTextField classIndcjTextField;
    private javax.swing.JTextField desenvolvedorjTextField;
    private javax.swing.JLabel desenvolvedornomejLabel;
    private javax.swing.JLabel idjLabel;
    private javax.swing.JTextField idjTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nomejLabel;
    private javax.swing.JTextField nomejTextField;
    private javax.swing.JLabel precojLabel;
    private javax.swing.JTextField precojTextField;
    private javax.swing.JButton removerjButton;
    private javax.swing.JButton salvarjButton;
    private javax.swing.JTable tabelaJogosCadastrojTable;
    private javax.swing.JLabel tipojLabel;
    private javax.swing.JTextField tipojTextField;
    // End of variables declaration//GEN-END:variables
}
