/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufmt.ic.alg3.videoJogos.view;

/**
 *
 * @author Moacyr
 */
public class LoginInicial extends javax.swing.JPanel {

    /**
     * Creates new form LoginInicial
     */
    public LoginInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(600, 450));
        setLayout(null);

        jButton1.setText("Entrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(180, 320, 73, 23);

        jLabel2.setText("Login:");
        add(jLabel2);
        jLabel2.setBounds(70, 250, 29, 14);

        jLabel3.setText("Senha:");
        add(jLabel3);
        jLabel3.setBounds(70, 280, 34, 14);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1);
        jTextField1.setBounds(110, 250, 150, 20);
        add(jPasswordField1);
        jPasswordField1.setBounds(110, 280, 150, 20);

        jPanel1.setBackground(new java.awt.Color(50, 50, 150));
        jPanel1.setForeground(new java.awt.Color(0, 0, 200));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("NosTeam");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 10, 110, 50);

        jLabel9.setText("Vídeo Jogos e muit diversão ");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(140, 80, 170, 14);

        add(jPanel1);
        jPanel1.setBounds(1, 20, 660, 131);

        jLabel4.setText("Iniciar sessão ");
        add(jLabel4);
        jLabel4.setBounds(70, 220, 80, 14);

        jLabel5.setText("Criar");
        add(jLabel5);
        jLabel5.setBounds(390, 220, 23, 14);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText(" O cadastro é gratuito e o programa é fácil de usar.");
        jLabel6.setToolTipText("");
        add(jLabel6);
        jLabel6.setBounds(350, 240, 280, 30);

        jLabel7.setText(" Continue para criar a sua conta Steam e baixar o Nosteam,");
        add(jLabel7);
        jLabel7.setBounds(350, 260, 300, 20);

        jLabel8.setText("uma boa solução digital para jogos e softwares.");
        add(jLabel8);
        jLabel8.setBounds(370, 280, 370, 20);

        jButton2.setText("Cadastre-se");
        add(jButton2);
        jButton2.setBounds(420, 320, 130, 23);

        jButton3.setText("Esqueceu a sua senha?");
        add(jButton3);
        jButton3.setBounds(90, 450, 170, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
