
package br.ufmt.ic.alg3.videoJogos.view;

import br.ufmt.ic.alg3.videoJogos.persistencia.UsuarioPersistencia;
import br.ufmt.ic.alg3.videoJogos.persistencia.arquivo.UsuarioPersistenciaArquivo;
import br.ufmt.ic.alg3.videoJogos.view.tableModel.UsuarioTableModel;

/**
 *
 * @author Moacyr
 */
public class ProcurarAmigos extends javax.swing.JPanel {

    UsuarioPersistencia banco = new UsuarioPersistenciaArquivo();
    /**
     * Creates new form ProcurarAmigos
     */
    public ProcurarAmigos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProcurarAmigosjTable = new javax.swing.JTable();
        conteudoProcurarAmigosjLabel = new javax.swing.JLabel();
        conteudoProcurarAmigos2jLabel = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(600, 450));
        setRequestFocusEnabled(false);
        setLayout(new java.awt.GridBagLayout());

        tabelaProcurarAmigosjTable.setModel(new UsuarioTableModel(banco.getAll()));
        jScrollPane1.setViewportView(tabelaProcurarAmigosjTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 433;
        gridBagConstraints.ipady = 310;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(12, 44, 34, 103);
        add(jScrollPane1, gridBagConstraints);

        conteudoProcurarAmigosjLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        conteudoProcurarAmigosjLabel.setForeground(new java.awt.Color(0, 0, 200));
        conteudoProcurarAmigosjLabel.setText("Procurar amigos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 24, 0, 0);
        add(conteudoProcurarAmigosjLabel, gridBagConstraints);

        conteudoProcurarAmigos2jLabel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        conteudoProcurarAmigos2jLabel.setForeground(new java.awt.Color(200, 0, 0));
        conteudoProcurarAmigos2jLabel.setText("Encontre amigos para socializar e se divertir!");
        conteudoProcurarAmigos2jLabel.setAlignmentX(0.5F);
        conteudoProcurarAmigos2jLabel.setBorder(new javax.swing.border.MatteBorder(null));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 24, 0, 0);
        add(conteudoProcurarAmigos2jLabel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel conteudoProcurarAmigos2jLabel;
    private javax.swing.JLabel conteudoProcurarAmigosjLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaProcurarAmigosjTable;
    // End of variables declaration//GEN-END:variables

   
}
